---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: data-pv
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gop-fileserver
  name: gop-fileserver
spec:
  containers:
  - image: kodekloud/fileserver
    name: gop-fileserver
    volumeMounts:
    - mountPath: /web
      name: data-store
    ports:
    -  containerPort: 8080
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gop-fs-service
  name: gop-fs-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31200
  selector:
    run: gop-fileserver
  type: NodePort
